# --- Identification de l'application ---
spring.application.name=SignatureNumeriqueBackend

# --- Configuration PostgreSQL (Données métier) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate & JPA ---
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ✅ Correction : Indispensable pour la gestion du type BYTEA sur PostgreSQL/Render
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# ✅ Correction : Désactivé pour forcer une gestion propre des transactions dans les Services
spring.jpa.open-in-view=false

# --- Configuration MongoDB (Audit immuable) ---
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# --- Configuration BREVO via Port 2525 ---
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=kabaconde5259@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}

# Sécurité SMTP pour le port 2525
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false

# Timeouts pour éviter le "Connection Timed Out"
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.debug=true

# --- Configuration Serveur ---
#server.port=${PORT:8080}
server.port=7860
server.ssl.enabled=false

# --- PKI & Sécurité métier (Projet de Master) ---
pki.stockage.chemin=${PKI_STOCKAGE:./coffre-pki}
pki.certificat.duree.minutes=365

# Configuration TSA (Horodatage électronique)
tsa.url=https://freetsa.org/tsr
tsa.enabled=true
tsa.hash-algorithm=SHA256

# Configuration HSM (SoftHSM2 pour environnement simulé)
hsm.pin=${HSM_PIN:1234}
hsm.pin.utilisateur=${HSM_PIN_USER:1234}


spring.servlet.multipart.resolve-lazily=true
# --- Divers & Performance ---
# ✅ Correction : Augmentation légère pour supporter des PDF signés plus lourds (Métadonnées/Certificats)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# ✅ Ajout : Gestion du pool de connexion pour éviter les fuites sur Neon/PostgreSQL
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

spring.main.allow-bean-definition-overriding=true
spring.mvc.async.request-timeout=30000

# Force l'IPv4 pour éviter les problèmes de résolution sur certains serveurs Cloud
spring.main.arguments=--java.net.preferIPv4Stack=true

spring.jackson.time-zone=Africa/Tunis
# Si tu utilises PostgreSQL pour les dates
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Tunis